export interface Recipe {
  slug: string
  title: string
  titleHindi: string
  description: string
  image: string
  time: string
  prepTime: number   // minutes — for schema
  cookTime: number
  difficulty: 'Easy' | 'Very Easy' | 'Medium'
  servings: number
  calories: number
  protein: string
  tag: string
  category: string
  ingredients: string[]
  steps: { title: string; description: string }[]
  tips: string[]
  keywords: string[]
}

export const RECIPES: Recipe[] = [
  {
    slug: 'tofu-makhani',
    title: 'Tofu Makhani',
    titleHindi: 'टोफू मखनी',
    description: 'Rich, creamy tomato-butter gravy with Hills Tofuda soy paneer. Restaurant-style taste, healthier ingredients.',
    image: '/images/recipe-makhani.png',
    time: '30 min',
    prepTime: 10,
    cookTime: 20,
    difficulty: 'Easy',
    servings: 4,
    calories: 280,
    protein: '18g',
    tag: 'Restaurant Style',
    category: 'Curry',
    keywords: ['tofu makhani', 'soy paneer makhani', 'vegan makhani', 'tofu curry'],
    ingredients: [
      '300g Hills Tofuda Soy Paneer — cubed',
      '2 tbsp butter (or vegan butter)',
      '1 large onion — finely chopped',
      '3 tomatoes — pureed',
      '1 tbsp ginger-garlic paste',
      '2 tsp kashmiri red chilli powder',
      '1 tsp garam masala',
      '1 tsp coriander powder',
      '½ tsp cumin seeds',
      '¼ cup cashew paste (soaked + blended)',
      '½ cup cream or coconut cream',
      'Salt to taste',
      'Fresh coriander for garnish',
      '1 tsp kasuri methi (dried fenugreek)',
    ],
    steps: [
      { title: 'Fry the tofu', description: 'Shallow fry tofu cubes in 1 tbsp oil until golden on all sides, about 4–5 minutes. Set aside on paper towel.' },
      { title: 'Make the base', description: 'In same pan, melt butter. Add cumin seeds, let splutter. Add onions, cook until golden — about 6 minutes.' },
      { title: 'Add aromatics', description: 'Add ginger-garlic paste, cook 2 minutes until raw smell disappears. Add all dry spices, stir 30 seconds.' },
      { title: 'Tomato gravy', description: 'Add tomato puree, cook on medium heat 8–10 minutes until oil separates from masala.' },
      { title: 'Cashew cream', description: 'Add cashew paste and cream. Stir well, simmer 3 minutes on low heat.' },
      { title: 'Add tofu + finish', description: 'Gently add fried tofu cubes. Crush kasuri methi between palms, add. Adjust salt. Simmer 2 minutes. Garnish with coriander.' },
    ],
    tips: [
      'Frying tofu first gives it a paneer-like texture that holds up in the gravy',
      'Cashew paste makes it creamier — skip cream if using cashews',
      'Kasuri methi at the end is the secret to restaurant taste',
    ],
  },
  {
    slug: 'tofu-bhurji',
    title: 'Tofu Bhurji',
    titleHindi: 'टोफू भुर्जी',
    description: 'Spiced scrambled tofu with onions, tomatoes, and Kumaoni masala. Perfect protein-packed breakfast ready in 15 minutes.',
    image: '/images/recipe-palak.png',
    time: '15 min',
    prepTime: 5,
    cookTime: 10,
    difficulty: 'Very Easy',
    servings: 2,
    calories: 220,
    protein: '22g',
    tag: 'Breakfast Favourite',
    category: 'Breakfast',
    keywords: ['tofu bhurji', 'soy paneer bhurji', 'vegan bhurji', 'tofu breakfast'],
    ingredients: [
      '200g Hills Tofuda Soy Paneer — crumbled',
      '1 medium onion — finely chopped',
      '1 tomato — chopped',
      '1 green chilli — chopped',
      '1 tsp ginger — grated',
      '½ tsp turmeric powder',
      '1 tsp cumin seeds',
      '½ tsp red chilli powder',
      '2 tbsp oil',
      'Salt to taste',
      'Fresh coriander — chopped',
      '½ tsp chaat masala (optional)',
    ],
    steps: [
      { title: 'Crumble the tofu', description: 'Crumble tofu with your hands into small chunks — like scrambled eggs. Do not over-crumble; keep some texture.' },
      { title: 'Temper the oil', description: 'Heat oil in a wide pan. Add cumin seeds, let splutter 30 seconds.' },
      { title: 'Cook onions', description: 'Add onions and green chilli. Cook on medium-high heat 4 minutes until translucent. Add ginger, cook 1 minute.' },
      { title: 'Add tomatoes + spices', description: 'Add tomato, turmeric, red chilli powder, salt. Cook 3 minutes until tomatoes soften.' },
      { title: 'Add crumbled tofu', description: 'Add crumbled tofu. Mix gently on high heat 2–3 minutes. Do not cover — let moisture evaporate for dry bhurji.' },
      { title: 'Finish', description: 'Add chaat masala if using. Garnish with fresh coriander. Serve hot with roti or toast.' },
    ],
    tips: [
      'High heat at the end gives the bhurji a slightly crispy texture',
      'Add 1 tbsp nutritional yeast for an eggy, umami flavour',
      'Works great as a paratha stuffing too',
    ],
  },
  {
    slug: 'soy-paneer-tikka',
    title: 'Soy Paneer Tikka',
    titleHindi: 'सोय पनीर टिक्का',
    description: 'Smoky, charred soy paneer marinated in yogurt and spices. The party starter that everyone asks the recipe for.',
    image: '/images/recipe-tikka.png',
    time: '35 min',
    prepTime: 20,
    cookTime: 15,
    difficulty: 'Medium',
    servings: 4,
    calories: 195,
    protein: '20g',
    tag: 'Party Starter',
    category: 'Starter',
    keywords: ['soy paneer tikka', 'tofu tikka', 'vegan tikka', 'plant based tikka'],
    ingredients: [
      '500g Hills Tofuda Soy Paneer — large cubes',
      '½ cup thick yogurt (or vegan curd)',
      '1 tbsp ginger-garlic paste',
      '2 tsp red chilli powder',
      '1 tsp cumin powder',
      '1 tsp coriander powder',
      '½ tsp garam masala',
      '1 tsp chaat masala',
      '1 tbsp mustard oil',
      'Juice of 1 lemon',
      '1 capsicum — cubed',
      '1 onion — cubed (layers separated)',
      'Salt to taste',
      'Chaat masala + lemon for serving',
    ],
    steps: [
      { title: 'Make the marinade', description: 'Mix yogurt, ginger-garlic paste, all spices, mustard oil, lemon juice and salt. Whisk until smooth.' },
      { title: 'Marinate tofu', description: 'Add tofu cubes, capsicum, onion. Coat everything well. Marinate minimum 20 minutes — 2 hours is better.' },
      { title: 'Skewer up', description: 'Thread tofu, capsicum and onion alternately on skewers. Do not pack too tight.' },
      { title: 'Grill or pan fry', description: 'Grill on high heat or use a grill pan with oil. Cook 3–4 minutes per side until charred marks appear.' },
      { title: 'Serve hot', description: 'Sprinkle chaat masala and fresh lemon juice. Serve with mint chutney and sliced onion rings.' },
    ],
    tips: [
      'Longer marination = deeper flavour. Overnight in fridge is best',
      'Pat tofu dry before marinating — absorbs marinade better',
      'Mustard oil gives authentic dhaba-style smokiness',
    ],
  },
  {
    slug: 'palak-tofu',
    title: 'Palak Tofu',
    titleHindi: 'पालक टोफू',
    description: 'Vibrant green spinach gravy with golden-fried tofu. The healthiest upgrade to palak paneer you never knew you needed.',
    image: '/images/recipe-palak.png',
    time: '25 min',
    prepTime: 8,
    cookTime: 17,
    difficulty: 'Easy',
    servings: 3,
    calories: 210,
    protein: '19g',
    tag: 'Health Special',
    category: 'Curry',
    keywords: ['palak tofu', 'spinach tofu', 'palak paneer vegan', 'tofu saag'],
    ingredients: [
      '300g Hills Tofuda Soy Paneer — cubed',
      '400g fresh spinach (palak) — blanched',
      '1 onion — roughly chopped',
      '3 garlic cloves',
      '1 inch ginger',
      '2 green chillies',
      '1 tsp cumin seeds',
      '½ tsp turmeric',
      '1 tsp coriander powder',
      '2 tbsp oil or ghee',
      '2 tbsp cream (optional)',
      'Salt + pinch of nutmeg',
    ],
    steps: [
      { title: 'Blanch spinach', description: 'Blanch spinach in boiling water 2 minutes. Transfer to ice cold water immediately. Blend smooth with green chillies.' },
      { title: 'Fry tofu', description: 'Fry tofu cubes in oil until golden. Set aside.' },
      { title: 'Make base', description: 'In same oil, add cumin seeds. Add onion, ginger, garlic — cook until golden. Add dry spices, cook 1 minute.' },
      { title: 'Add spinach puree', description: 'Add blended spinach. Cook on medium 5 minutes, stirring often.' },
      { title: 'Combine', description: 'Add fried tofu. Stir gently. Add cream if using. Simmer 3 minutes. Finish with pinch of nutmeg and salt.' },
    ],
    tips: [
      'Ice bath after blanching keeps the bright green colour',
      'Do not overcook spinach gravy — colour turns dull',
      'A tiny piece of coal for dhungar smoke makes it restaurant-level',
    ],
  },
  {
    slug: 'tofu-stir-fry',
    title: 'Tofu Stir Fry',
    titleHindi: 'टोफू स्टर फ्राय',
    description: 'Crispy tofu with vegetables in a punchy sauce. Fast, filling, gym-friendly. Done in 20 minutes.',
    image: '/images/recipe-stirfry.png',
    time: '20 min',
    prepTime: 8,
    cookTime: 12,
    difficulty: 'Easy',
    servings: 2,
    calories: 260,
    protein: '24g',
    tag: 'Gym Favourite',
    category: 'Quick',
    keywords: ['tofu stir fry', 'crispy tofu', 'high protein tofu', 'tofu vegetable'],
    ingredients: [
      '300g Hills Tofuda Soy Paneer — pressed, cubed',
      '1 capsicum — sliced',
      '1 carrot — julienned',
      '100g broccoli florets',
      '3 garlic cloves — minced',
      '1 tsp ginger — grated',
      '3 tbsp soy sauce',
      '1 tbsp sesame oil',
      '1 tsp rice vinegar',
      '1 tsp chilli flakes',
      '1 tsp cornflour',
      '2 tbsp vegetable oil',
      'Sesame seeds + spring onion to garnish',
    ],
    steps: [
      { title: 'Press the tofu', description: 'Wrap tofu in kitchen towel, press 10 minutes to remove moisture. This is what makes it crispy.' },
      { title: 'Make sauce', description: 'Mix soy sauce, sesame oil, rice vinegar, chilli flakes, cornflour with 2 tbsp water. Keep aside.' },
      { title: 'Crisp the tofu', description: 'Cook tofu in hot oil on high heat, undisturbed 3 minutes each side until golden and crispy. Remove.' },
      { title: 'Stir fry veggies', description: 'In same wok on high heat, add garlic and ginger — 30 seconds. Add all vegetables, stir fry 3–4 minutes keeping crunch.' },
      { title: 'Combine', description: 'Add tofu back. Pour sauce over. Toss everything 1–2 minutes until coated and glossy. Garnish, serve immediately.' },
    ],
    tips: [
      'Pressing tofu is non-negotiable for crispy results',
      'High heat throughout — do not lower it',
      'Serve over brown rice for complete protein meal',
    ],
  },
  {
    slug: 'tofu-butter-masala',
    title: 'Tofu Butter Masala',
    titleHindi: 'टोफू बटर मसाला',
    description: 'Silky, indulgent tomato-cashew gravy. Looks like 3-hour cooking. Takes 25 minutes.',
    image: '/images/recipe-butter.png',
    time: '25 min',
    prepTime: 5,
    cookTime: 20,
    difficulty: 'Easy',
    servings: 4,
    calories: 295,
    protein: '17g',
    tag: 'Crowd Pleaser',
    category: 'Curry',
    keywords: ['tofu butter masala', 'soy paneer butter masala', 'vegan butter chicken', 'tofu gravy'],
    ingredients: [
      '400g Hills Tofuda Soy Paneer — cubed',
      '4 tomatoes — roughly chopped',
      '1 large onion — roughly chopped',
      '15 cashews — soaked',
      '3 garlic cloves',
      '1 inch ginger',
      '2 tbsp butter',
      '1 tsp sugar',
      '1 tsp kashmiri chilli powder',
      '½ tsp turmeric',
      '1 tsp garam masala',
      '½ cup cream',
      '1 tsp kasuri methi',
      'Salt to taste',
    ],
    steps: [
      { title: 'Pressure cook base', description: 'Pressure cook onion, tomatoes, garlic, ginger, cashews with ½ cup water — 2 whistles. Cool completely.' },
      { title: 'Blend smooth', description: 'Blend cooked mixture until completely smooth. Pass through strainer for silky texture.' },
      { title: 'Fry tofu', description: 'Shallow fry tofu in butter until golden. Set aside.' },
      { title: 'Cook the gravy', description: 'In same pan, add butter. Pour strained gravy. Add all spices, sugar, salt. Cook 8–10 minutes on medium.' },
      { title: 'Finish', description: 'Add cream, kasuri methi (crushed). Add fried tofu. Simmer 3 minutes. Adjust consistency with water.' },
    ],
    tips: [
      'Straining the gravy is what gives it that dhaba-smooth texture',
      'Sugar balances the tomato tartness — do not skip',
      'Double the batch and freeze the gravy — lifesaver for busy days',
    ],
  },
]

export function getRecipeBySlug(slug: string): Recipe | undefined {
  return RECIPES.find(r => r.slug === slug)
}
